name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v1

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: client
        run: |
          cd ~/actions-runner/_work/task-manager/task-manager/ClientApp/
          npm ci
          ionic build --prod
          rsync -r /root/actions-runner/_work/task-manager/task-manager/ClientApp/dist/* /var/www/tenni-venni/

      - name: backend
        run: |
          # pm2 start "dotnet" --name "backend" -- "TaskManager.dll"
          pm2 stop backend
          cd ~/actions-runner/_work/task-manager/task-manager/
          dotnet publish -c release -o ~/tenni-venni-dotnet/ -r linux-x64
          cd ~/tenni-venni-dotnet/
          pm2 start backend
