name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

     

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
